### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by SoftCreatR** [hark/mediaelement-plugins#1]
Hi,

would it be possible to update your plugins? Especially a working FontAwesome integration would be awesome :)

**Comment by MatthewCallis** [comment]
What specifically is broken?

**Comment by SoftCreatR** [comment]
It's just completely outdated.

**Comment by MatthewCallis** [comment]
Closing this, please raise specific, actual issues, or use an older version of ME/FA.

**Comment by SoftCreatR** [comment]
For example: The CSS declarations you overwrote are partially no longer existent in ME. Same for FA.
